# Generated by Django 4.2.15 on 2024-10-17 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_x', models.CharField(max_length=100)),
                ('player_o', models.CharField(max_length=100)),
                ('board', models.JSONField(default=list)),
                ('current_turn', models.CharField(default='X', max_length=1)),
                ('winner', models.CharField(blank=True, max_length=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
