# Generated by Django 4.2.15 on 2024-10-20 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0007_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Match',
        ),
    ]
