# Generated by Django 4.2.15 on 2024-10-20 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tictactoe', '0010_delete_match'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_key', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('board', models.JSONField(default=dict)),
                ('current_turn', models.CharField(default='X', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player_o', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_o', to=settings.AUTH_USER_MODEL)),
                ('player_x', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_x', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
