# Generated by Django 4.2.15 on 2024-10-20 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tictactoe', '0011_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.BooleanField(blank=True, max_length=1, null=True),
        ),
    ]
